[build]
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-store"
